# wrangler.toml
name = 'hegerdes-mail-worker'
main = "src/index.ts"
compatibility_date = "2023-03-16"

workers_dev = false

[vars]
BLACKLIST = "[\"tiscali.it\"]"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "hegerdes-mix"         # Set this to your R2 bucket name. Required
preview_bucket_name = "hegerdes-mix" # Set this to your preview R2 bucket name. Can be equal to bucket_name. Optional

[observability.logs]
enabled = true
